#!/bin/sh

DBNAME=plruby_test

dropdb $DBNAME

createdb $DBNAME

"${RUBY-ruby}" b.rb "$1"
psql -q -n -X $DBNAME < test_mklang.sql

psql -q -n -X $DBNAME < test_setup.sql

psql -q -n -X -e $DBNAME < test_queries.sql > test.out 2>&1

if cmp -s test.expected test.out; then
    echo "    Tests passed O.K."
else
    echo "    Tests failed - look at diffs between"
    echo "    test.expected and test.out"
fi
